{
 "title": "Elbencho Monitoring with Dropdown",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "runname",
    "label": "Run Name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Elbencho Single Stats (Current)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(elbencho.$runname.*.IOPS)"
    }
   ]
  },
  {
   "title": "Total Throughput ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(elbencho.$runname.*.MiB_per_s)"
    }
   ]
  },
  {
   "title": "IO Latency Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "elbencho.$runname.read.Lat_IO_us"
    }
   ]
  },
  {
   "title": "Percentage Complete",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(elbencho.$runname.*.Done%)"
    }
   ]
  },
  {
   "title": "Data Statistics",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(elbencho.$runname.read.DoneBytes, 'Data Read')"
    },
    {
     "target": "alias(elbencho.$runname.write.DoneBytes, 'Date Written')"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "p99" ] } },
   "targets": [
    { "target": "elbencho.$runname.*.CPU" }
   ]
  },
  {
   "title": "Block Size Read (Avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(summarize(elbencho.$runname.read.IOPS, '1m', 'sum', true), 'IOPS')"
    },
    {
     "target": "alias(summarize(elbencho.$runname.read.MiB_per_s, '1m', 'sum', true), 'MiB/s')"
    }
   ]
  },
  {
   "title": "Block Size Write (Avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(summarize(elbencho.$runname.write.IOPS, '1m', 'sum', true), 'IOPS')"
    },
    {
     "target": "alias(summarize(elbencho.$runname.write.MiB_per_s, '1m', 'sum', true), 'MiB/s')"
    }
   ]
  },
  {
   "title": "IO Latency Write",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "elbencho.$runname.write.Lat_IO_us"
    }
   ]
  },
  {
   "title": "Read Percentage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "elbencho.$runname.read.Phase" }
   ]
  },
  {
   "title": "Active Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "averageSeries(elbencho.$runname.*.Active)"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "averageSeries(elbencho.$runname.*.RuntimeMS)"
    }
   ]
  },
  {
   "title": "Elbencho Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Elbencho Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "elbencho.$runname.read.IOPS" }
   ]
  },
  {
   "title": "Elbencho Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "elbencho.$runname.write.IOPS" }
   ]
  },
  {
   "title": "Elbencho Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "target": "elbencho.$runname.read.MiB_per_s"
    }
   ]
  },
  {
   "title": "Elbencho Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "target": "elbencho.$runname.write.MiB_per_s"
    }
   ]
  },
  {
   "title": "Elbencho Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "elbencho.$runname.read.Lat_IO_us"
    }
   ]
  },
  {
   "title": "Elbencho Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "elbencho.$runname.write.Lat_IO_us"
    }
   ]
  }
 ]
}